### ISSUE TITLE
The GPL license will significantly hurt adoption.

### ISSUE THREAD

**Issue by Asmageddon** [jonsneyers/FLIF#9] opened 2015-10-02 18:10 UTC
Namely, it renders it unusable for a wide array of uses, and, being the only implementation, with quite likely relatively few people interested in re-implementing it(it's not well known, or used), this means that no one will be creating FLIF images, and no one will be capable of using FLIF images. 

I suggest keeping the specification as GPL, and re-implementing the library as LGPL, or MIT, instead of a viral license like GPL.

**Comment by jdalbey** [comment] 2015-10-02 18:59
I agree with Asmageddon.

**Comment by tdkohlbeck** [comment] 2015-10-02 19:00
The [HN discussion](https://news.ycombinator.com/item?id=10317790) has many insightful comments relating to this issue, including the following choice comments:

> I think the right avenue is to keep the license GPL but provide a permissive as-is use license. The idea is that you want people making improvements to the algorithm to contribute those back for the public's benefit rather than charging people for their "upgraded" version. A separate unmodified-use license could be much more permissive in the use of algorithm as-is for compressing and decompressing images.

@scottmp10
 
>I think the concerns about the licensing are a bit premature - honestly, this is currently a research project, not a practical replacement for existing image formats. The licensing is only one of several impediments to adoption.

@tfinniga
 
>I think even Stallman would've advocated something like the MIT or BSD license for something like this -- having a patent-unencumbered alternative to formats like JPEG 2000 being used seems to be more important to a lot of Free Software people. In other words, the advantage of having widely-used file formats that are accessible to free software programs are considered greater than the benefits of having software become libre in order to use GPL'd file format libraries. Stallman defended the use of a non-copyleft license for Ogg/Vorbis on those grounds:
[https://lwn.net/2001/0301/a/rms-ov-license.php3]()

@cwyers

> It has nothing to do with requirement of code sharing. It's all about realism. So far there has been 0 successful file formats/codecs with GPL reference implementation and there is no reason to except FLIF to buck the trend.

@zokier

> RMS himself was against putting such formats/codecs in GPL. Suggested Apache 2 license.

@nickpsecurity

I'll leave any fact-checking to others.

**Comment by CounterPillow** [comment] 2015-10-02 19:22
It's also legally [impossible to comply with the GPLv3 on iOS](https://www.fsf.org/news/2010-05-app-store-compliance/), so the reference implementation could not legally be redistributed as part of iOS applications.

Inclusion into less restrictively licensed imaging libraries such as FreeImage, ImageMagick and Python Imaging/Pillow as well as DevIL/OpenIL would also become impossible, and would require build-time licensing preset nonsense like FFmpeg has.

At the least, please choose LGPL2. Best would be something Apache2/MIT/zlib-like. Apache2 has the benefit of also including a patent termination clause, which might be useful.

**Comment by ke7ofi** [comment] 2015-10-02 20:13
:+1: @Asmageddon (Though I’d personally rather just see an MIT license, their suggestion is likely the most compatible with everyone’s goals.)

**Comment by Wallacoloo** [comment] 2015-10-02 20:33
Is this not a duplicate of #3? IMO, @Asmageddon should close this issue and just use the other thread so that all the discussion on licensing takes place in one area and we don't have things getting needlessly repeated.

In any case, that other thread has useful links and quotations from the author so that you might be able to understand his point of view.

**Comment by ke7ofi** [comment] 2015-10-02 20:36
Sorry, I didn’t see that one. I agree with @Wallacoloo.

**Comment by kozross** [comment] 2015-10-02 22:36
I think that 'hurting adoption' by corporate abusers is not something I'd be against. Stand for copyleft, stand for freedom, and if the tool is worth it, corps *will* bend. Note that the Linux kernel managed this, and I don't see *anyone* whining to *them* about copyleft ruining their adoption among their corporate masters. :tongue:

**Comment by pizzamaker** [comment] 2015-10-02 22:43
I have to agree with @kozross on this one. If proprietary makers don't use this format, it's their loss. FLIF will still be great and be used in projects that care about its users.

**Comment by vyp** [comment] 2015-10-02 22:46
I strongly disagree. Apple should be the one to comply with freedom, not the other way around. Right now we have a technologically superior format, if other entities do not want to use it due to the copyleft, that's there loss. The superior format features can be used to put pressure on them. We shouldn't give up this unique opportunity so quickly and early.

People are talking about hurt chances of adoption. But now that there is great interest in this format, it can be used in its advantage, and for the advantage of copyleft and free software.

**Comment by stuartpb** [comment] 2015-10-03 01:35
I actually agree that, for right now, while the format is unready for adoption, the GPLv3 *is* the right choice - since the format is premature, you don't *want* easier adoption yet, and if a program is going to try to use it, **you _do_ want the code copyleft-tainted, so that the obsolete version of the format can't become an irrevocable part of the codebase** (it will always be possible to fix with a patch).

Once the format has settled to a degree that it's ready for adoption, then you'll want to relicense the project, and that will have its own issues without a CLA (which is what I'm going to post about right now) - but, for now, GPL is the way to go.

**Comment by ke7ofi** [comment] 2015-10-03 01:40
Good idea, @stuartpb.

@kozross what about corporate users (sans abuse)? Closed-source isn’t inherently bad; it’s just inferior.

**Comment by DominikDeak** [comment] 2015-10-03 01:48
I'm involved in developing a graphics design app and I am always on the lookout for new file formats to support. However, GPL makes this an impossibility for some libraries, such as this one. Perhaps the authors should reconsider releasing the lib under BSD.

**Comment by kozross** [comment] 2015-10-03 02:38
@ke7ofi I beg to differ. Nonfree (I *refuse* to use the disgusting and corporate-appeasing vocabulary of the open saucers) software *is* inherently bad, and evidence of this is all around us, every day. Ignoring ethical implications won't make them go away.

**Comment by jonsneyers** [comment] 2015-10-03 07:53
Closing this one, feel free to discuss further in https://github.com/jonsneyers/FLIF/issues/3

**Closed by jonsneyers** 2015-10-03 07:53 UTC

**Comment by ke7ofi** [comment] 2015-10-03 22:05
@kozross Easy there, RMS. Things like copyright laws are silly, but by the same token, people aren’t ethically obligated (and certainly shouldn’t be legally obligated) to release their source code. I use almost exclusively OSS, but I’m not going to condemn someone who wants to try making money that way. I just don’t buy their product if I can avoid it (exceptions include things like cars, where there aren’t really any OSS alternatives yet (though hopefully Local Motors or someone similar will fix that)).

**Comment by kozross** [comment] 2015-10-03 22:25
@ke7ofi On that point, we differ substantially. I *do* condemn people who want to make money depriving people of their freedom, and will continue to do so. Just not here, since it's obvious that corporate appeasement is the goal of this project, judging by the wording of its CLA.

**Comment by ke7ofi** [comment] 2015-10-03 23:11
@kozross Why do you think that? I know a decent number of people agree with you, but I’ve never understood why? I assume it’s a better reason than “This is selfish; therefore evil.”.

**Comment by vyp** [comment] 2015-10-04 00:35
@ke7ofi One can choose to not release anything if they do not want to. But once they do decide to release a program for public use, they should also give the public the ability to use, study, modify, and release those modifications etc. as they wish. Otherwise, this is just unethical. Of course, you are free to disagree with that, but if you or anyone else is interested for more about why RMS and co think like this, you should read some of Stallman's essays: https://www.gnu.org/philosophy/fsfs/rms-essays.pdf.

**Comment by ke7ofi** [comment] 2015-10-04 04:14
230 pages? I’m glad that we have somebody on the extreme end of the spectrum pushing for more open software (He might just barely balance out the illegal tractor repair people.), but I have to wonder what sort of person would spend that much time writing similar works. (Have you seen https://rms.sexy/?)

**Comment by vyp** [comment] 2015-10-04 04:28
Well not all of it... that just lists a lot of the essays as a book. Maybe https://www.gnu.org/philosophy/ instead?
